config/routes.rb
Rednote::Application.routes.draw do

  resources :documents, :only => [:index, :create, :show, :destroy, :update]

  match '/mails', :to => 'mails#index'
  match '/mails/interview', :to => 'mails#interview'
  match '/mails/invite', :to => 'mails#invite'

  match '/calendar(/:year(/:month))' => 'projects#index', 
    :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  root :to => "projects#index"
  mount Ckeditor::Engine => '/ckeditor'

  resources :projects
  resources :events do
    collection do
      get 'get_events'
      post 'move'
      post 'resize'
    end
  end
    
  
  resources :debits, :only => [:new, :destroy] do
    collection do
      post 'unwaiting'
    end
  end

  resources :books, :only => [ :new, :index, :create, :show ] do
    collection do 
      post 'borrow'
    end
  end

  resources :comments, :only => [:new, :index, :create, :destroy, :update] do 
    collection do 
      get 'dono'
    end
  end

  resources :likes, :only => [:create, :update, :destroy]
  resources :attachements, :only => [:create]

  devise_for :users
  resources :users, :only => [:show] do
    member do
      get 'mytags'
      get 'mytasks'
      get 'mycomments'
      get 'page'
      get 'myats'
    end
    collection do
      get 'nickname'
      match 'avatar'
      match 'avatar_update'
      match 'nickname_update'
      get 'search_nickname'
      get 'search_email'
      match 'crop_update'
    end
  end

  resources :notes do
    collection do
      get 'page'
      get 'taglist'
    end
  end

  resources :tasks do
    member do
      get 'show_partial'
    end
    collection do
      get 'mytasks'
      get 'history'
      get 'discuss'
      get  'set_status'
      post 'set_tag'
      get 'assign'
    end
  end

end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id         :integer(4)      not null, primary key
#  user_id    :integer(4)
#  summary    :text
#  created_at :datetime        not null
#  updated_at :datetime        not null
#  message    :integer(4)      default(0)
#

class Note < ActiveRecord::Base
  acts_as_commentable
  acts_as_taggable_on :tags

  belongs_to :user
  has_many :likes, :dependent => :destroy
  has_many :attachements, :dependent => :destroy

  has_many :infos, :dependent => :destroy, :as => :message

  validates :summary, :presence => true,
                      :length   => { :maximum => 500 }
  validates :user_id, :presence => true
  attr_accessible :summary, :tag_list
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  include ERB::Util
  before_filter :authorized_user, :only => :destroy

  # GET /notes
  # GET /notes.json
  def index
    @note = Note.new

    cookies = {
      "limit" => 20,
      "offset" => 20, # note offset
      "current_user_id" => current_user.id
    }

    @notes = Note.where('').offset(0).limit(cookies[:limit]).reverse_order
    @tags = Note.tag_counts.map {|tag| tag.name}

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /notes/taglist
  # get tags
  def taglist
    @tags = Note.tag_counts.map {|tag| tag.name}

    respond_to do |format|
      format.json { render json: @tags }
    end
  end

  # GET /notes/page
  # get next page by ajax request
  def page
    @notes = Note.offset(cookies[:offset].to_i).limit(cookies[:limit]).reverse_order
    cookies[:offset] = @notes.size + cookies[:offset].to_i

    respond_to do |format|
      if @notes.count() > 0
        format.js
      else
        format.js { render :nothing => true }
      end
    end
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
    @note = Note.find(params[:id])
    @comments = @note.comments
    @messages = Array.new

    @note.infos.each do |message|
      @messages << message
    end

    @comments.each do |comment|
      comment.infos.each do |message|
        @messages << message
      end
    end

    @messages.each do |message|
      if message.user_id == current_user.id
        message.read = 0 # 0 means read and 1 means unread
        message.refer = 0
        message.save!
      end
    end

    respond_to do |format|
      format.html # show.html.erb
      format.js # show.js.erb
    end
  end

  # GET /notes/new
  # GET /notes/new.json
  def new
    respond_to do |format|
      format.html
    end
  end

  # GET /notes/1/edit
  def edit
    @note = Note.find(params[:id])
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = current_user.notes.build(params[:note])
    @attachids = params[:attachments].split(',')

    @at_users = @note.summary.scan(/@[a-zA-Z0-9_]+/)
    
    @note.summary = string_replace(3 , html_escape(@note.summary)) # repalce the string

    if @note.save
      @at_users.each do |at_user|
        user = User.find_by_sql("SELECT users.* FROM users WHERE nickname='#{at_user.from(1)}'") #check user is exist
        if user.size == 1 #because note can not edit so the create note unexist in message table
          @message = @note.infos.create( {
            :user_id => user[0].id,
            :message => @note,
            :refer => 1
          } )
          broadcast "/ats/new/#{@message.user_id}", "{ note_id: #{@note.id}, meg_type: 'at_in_note' }"
        end
      end
      @attachids.each do |attachid|
        attach = Attachement.find(attachid)
        attach.note_id = @note.id and attach.save if not attach.nil?
      end

      broadcast '/notes/new', %Q/ { nickname: "#{current_user.nickname}", status: true } /

          cookies[:offset] = cookies[:offset].to_i + 1
      respond_to do |format|
        format.html { redirect_to notes_path, notice: 'Note was successfully created.' }
        format.js 
      end
    else
      broadcast '/notes/new', %Q/ { status: false, errors: #{@note.errors.to_json} } /
      respond_to do |format|
        format.html { redirect_to notes_path, notice: 'Note creation was failed.' }
        format.js 
      end
    end
  end

  # PUT /notes/1
  # PUT /notes/1.json
  def update
    @note = Note.find(params[:id])

    respond_to do |format|
      if @note.update_attributes(params[:note])
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note = Note.find(params[:id])
    @note.destroy

    broadcast '/notes/destroy', %Q/ { "nickname" : "#{current_user.nickname}" } /

    cookies[:offset] = cookies[:offset].to_i - 1
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.js
    end
  end

  private
  def authorized_user
    note = current_user.notes.find_by_id(params[:id])
    redirect_to root_path if note.nil?
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_attach_image.html.haml
%a{ "data-toggle" =>"modal", :href => "#attach_image#{item.id}"}
  .thumbnail
    =image_tag "#{item.url.url}"

  .modal.hide.fade{:id => "attach_image#{ item.id }"}
    .modal-header
      %a.close(data-dismiss="modal") ×
      %h3 细节

    .modal-body
      =image_tag "#{item.url.url}" 

    .modal-footer
      %a.close.btn(href="#" data-dismiss="modal") 关闭

app/views/notes/_attachments.html.haml
-images = items.select do |item| 
  -item.url.url.end_with?('jpg', 'png', 'gif', 'jpeg') 
-docs = items - images 

.row-fluid
  .span4
    -if images.size > 1
      .carousel(id="attach_carousel#{noteid}")
        .carousel-inner
          -images.each_index do |idx|
            -cls = 'active' if idx == 0
            %div{:class => ["item", cls]}
              =render :partial => "notes/attach_image", :locals => { :item => images[idx] } 

        %a.carousel-control.left(href="#attach_carousel#{noteid}" data-slide="prev") &lsaquo;
        %a.carousel-control.right(href="#attach_carousel#{noteid}" data-slide="next") &rsaquo;

    -elsif images.size == 1
      =render :partial => "notes/attach_image", :locals => { :item => images[0] } 

  -docs.each do |item|
    .thumbnail.span8
      %a(href="#{item.url.url}")= item.url.url.sub(/.*\//, '') 

app/views/notes/_list.html.haml
-# encoding: utf-8
-@notes.each do |note|
  =render :partial => 'notes/note', :locals => { :note => note }

app/views/notes/_note.html.haml
-# encoding: utf-8
%div(id="note#{note.id}")
  %hr
  .row-fluid
    -note_user = User.find(note.user_id)
    .span1
      =link_to image_tag(note_user.avatar_url(:small), :class => "avatar",
        :title => "#{note_user.nickname}"), user_path(note_user), :method => :get

    .span11.item
      .content
        %span(style="word-wrap: break-word;")
          =note.summary.html_safe

        -if note.attachements.size > 0
          =render :partial => "notes/attachments",
            :locals => { :noteid => note.id, :items => note.attachements } 

        .note_tags
          -note.tag_list.each do |tag|
            %span.label.label-info= "#{tag}"

      .pull-right
        -if current_user.id==note_user.id
          = link_to '删除', "#removenote#{note.id}",
            'data-toggle' => "modal", :class => 'toremove small-link'
          .noteremove.modal.hide.fade{:id => "removenote#{note.id}", :noteid => "#{note.id}", :style => "display: none;"}
            .modal-header
              %a.close(data-dismiss="modal") ×
              %h3 确定删除吗？
            .modal-footer
              = link_to '删除', note, :method => "delete",  "data-dismiss" => "modal", :class => "btn", :remote => true
              %a.btn{:href => "close", "data-dismiss" => "modal"} 取消
        %i.vline |
        -my_like = current_user.likes.find_by_note_id(note.id)
        -if not my_like
          =link_to '我想读', likes_path(:note_id => note.id), :method => :post,
            :remote => true, :class => "tags small-link"

        -elsif not my_like.status and controller.action_name == "mytags"
          =link_to '取消标记', like_path(my_like), :method => :delete,
            :remote => true, :class => "tags small-link"
          =link_to '读完？', like_path(my_like), :method => :put, :remote => true, :class => "tags"
        -elsif not my_like.status and not controller.action_name == "mytags small-link"
          已标记
        -else
          已读完

        - myclass = "small-link"
        - myclass += " label-warning" if current_user.id == note.user_id and not note.message == 0
        %i.vline |
        = link_to "评论(#{note.comments.count})", comments_path(:note_id => note.id), 
          :remote => true, :class => myclass, :id => "comments_link#{note.id}",
          "data-toggle" => "collapse", "data-target" => "\#comments_list#{note.id}"

      .live-timestamp(data-notetime="#{note.created_at}")
      %br
      %div.collapse.fade.framed(style="height: 0px;" id="comments_list#{note.id}")

app/views/notes/_sidebar.html.erb
<div class="board">
  <%= render :partial => 'users/userinfo', :locals => { :user => current_user } %>

  <h3>本周任务</h3>

  <% totalpoint = Task::MAX_WEEK_TASK_TIME %>
  <% donepoint = 0 %>
  <% Task.find_by_sql("select * from tasks where assigned_to=#{current_user.id} and ( status < 2 or (status=2 and finish_at >= '#{Date.today.beginning_of_week.to_datetime.to_formatted_s(:db)}'))").each do |task| %>
    <% donepoint += task.estimate.to_f if task.status == Task::DONE %>
    <%= render :partial => 'tasks/note', :locals => { :task => task, :show => :todo } if task.status != 2 %>
  <% end %>
  
  <h4>任务/时间进度</h4>
  <div id="taskprogress" class="progress small-progress progress-striped">
    <div class="bar" style="width: <%= 100.0*donepoint/totalpoint %>%;" total=<%= totalpoint %> done=<%= donepoint %> ></div>
  </div>
  <div id="timeprogress" class="progress small-progress progress-info progress-striped">
    <div class="bar" style="width: 1%;"></div>
  </div>
</div>

app/views/notes/backbone.html.haml
.board
  #notes

:javascript
  $(function() {
    // Rednote is the app name
    window.router = new Rednote.Routers.NotesRouter({notes: #{@notes.to_json.html_safe}});
    Backbone.history.start();
  });

app/views/notes/create.js.erb
<%# encoding: utf-8 %>

(function() {
  <% if @note.valid?  %>
    var $notes = $('#notes_content ul.list');
    var id;

    $notes.prepend( "<%= j render :partial => 'notes/note', :locals => { :note => @note } %>" );

    $('#new_note')[0].reset();
    $('#new_note').find('#note_attachments').attr('value', '');
    $('#new_note').find('#note_tag_list').attr('value', '');
    $('#pending_tag_list').empty();
    $('#filelist').empty();
    $('#notes_content').find('ul.list div:first').hide().fadeIn(1000);

    var obj = $('#note<%= @note.id %>');
    removeAlert.bindRemoveAlert(obj);
  <% end %>
}());

app/views/notes/destroy.js.erb
<%# encoding: utf-8 %>

(function() {
  $('#note<%= @note.id%> ').fadeOut('fast', function(){
    $(this).remove();
  } );
}());

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<script type="text/javascript">
  $(function() {
      window.commentRouter = new Rednote.Routers.CommentsRouter();
      window.noteRouter = new Rednote.Routers.NotesRouter({
        notes: <%= @notes.to_json.html_safe %>,
        current_user: <%= @current_user.to_json.html_safe %>
      });
      Backbone.history.start({root: '/notes'}); 
  });
</script>

app/views/notes/new.html.erb
<div class="block">
  <div class="secondary-navigation"></div>
  <div class="content">
    <%= render "#{controller.action_name}_form" %>
  </div>
</div>

app/views/notes/page.js.erb
(function() {
  var $notes = $('#main-contents ul.list');
  $notes.append( "<%= j render 'notes/list' %> " );

  <% if @notes.size > 0 %>
      setTimeout( function() {
        <% @notes.each do |note| %>
          var obj = $('#note<%= note.id %>');
          removeAlert.bindRemoveAlert(obj);
        <% end %>
      }, 100 );
    <% end %>
});

app/views/notes/show.html.haml
-# encoding: utf-8
%div.well(id="note#{@note.id}")
  .row-fluid
    - note_user = User.find(@note.user_id)
    .span1
      = link_to image_tag(note_user.avatar_url(:small), :class => "avatar", :title => "#{note_user.nickname}"), user_path(note_user), :method => :get

    .span11.item
      .content
        %span(style="word-wrap: break-word;")
          = @note.summary.html_safe

        - if @note.attachements.size > 0
          = render :partial => "notes/attachments",
            :locals => { :noteid => @note.id, :items => @note.attachements } 

      .pull-right
        - if current_user.id==note_user.id
          = link_to '删除', @note, :confirm => "Are you sure?", method: :delete, 
            :remote => true, :class => 'toremove small-link'
        %i.vline |
        - my_like = current_user.likes.find_by_note_id(@note.id)
        - if not my_like
          = link_to '我想读', likes_path(:note_id => @note.id), :method => :post,
            :remote => true, :class => "tags small-link"

        - elsif not my_like.status and controller.action_name == "mytags"
          = link_to '取消标记', like_path(my_like), :method => :delete,
            :remote => true, :class => "tags small-link"
          = link_to '读完？', like_path(my_like), :method => :put, :remote => true, :class => "tags"
        - elsif not my_like.status and not controller.action_name == "mytags small-link"
          已标记
        - else
          已读完

      .live-timestamp(data-notetime="#{@note.created_at}")
  .row-fluid
    #comments_list.well
      = render 'comments/comment_box'

app/views/notes/show.js.erb
(function() {
    $num = $('#update_info');
    var new_num = <%= current_user.infos.sum("refer")%>;
    $num.text( $num.text().replace(/\d+/, new_num) );
    if( Number(new_num) === 0 ) {
      $num.attr("style","display:none;");
    }
}());