config/routes.rb
Rednote::Application.routes.draw do

  resources :documents, :only => [:index, :create, :show, :destroy, :update]

  match '/mails', :to => 'mails#index'
  match '/mails/interview', :to => 'mails#interview'
  match '/mails/invite', :to => 'mails#invite'

  match '/calendar(/:year(/:month))' => 'projects#index', 
    :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  root :to => "projects#index"
  mount Ckeditor::Engine => '/ckeditor'

  resources :projects
  resources :events do
    collection do
      get 'get_events'
      post 'move'
      post 'resize'
    end
  end
    
  
  resources :debits, :only => [:new, :destroy] do
    collection do
      post 'unwaiting'
    end
  end

  resources :books, :only => [ :new, :index, :create, :show ] do
    collection do 
      post 'borrow'
    end
  end

  resources :comments, :only => [:new, :index, :create, :destroy, :update] do 
    collection do 
      get 'dono'
    end
  end

  resources :likes, :only => [:create, :update, :destroy]
  resources :attachements, :only => [:create]

  devise_for :users
  resources :users, :only => [:show] do
    member do
      get 'mytags'
      get 'mytasks'
      get 'mycomments'
      get 'page'
      get 'myats'
    end
    collection do
      get 'nickname'
      match 'avatar'
      match 'avatar_update'
      match 'nickname_update'
      get 'search_nickname'
      get 'search_email'
      match 'crop_update'
    end
  end

  resources :notes do
    collection do
      get 'page'
      get 'taglist'
    end
  end

  resources :tasks do
    member do
      get 'show_partial'
    end
    collection do
      get 'mytasks'
      get 'history'
      get 'discuss'
      get  'set_status'
      post 'set_tag'
      get 'assign'
    end
  end

end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer(4)      not null, primary key
#  title            :string(50)      default("")
#  comment          :text
#  commentable_id   :integer(4)
#  commentable_type :string(255)
#  user_id          :integer(4)
#  created_at       :datetime        not null
#  updated_at       :datetime        not null
#

class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at ASC'

  validates :user_id,        :presence => true
  validates :commentable_id, :presence => true
  validates :title,   :length       => { :maximum => 30 }
  validates :comment, :presence     => true,
                      :length       => { :maximum => 10000 }

  attr_accessible :title, :comment, :commentable_id, :commentable_type

  has_many :infos, :dependent => :destroy, :as => :message

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include ERB::Util
  before_filter :authorized_user, :only => [:destroy, :update]

  # GET /comments
  # GET /comments.json
  def index
    @note = Note.find(params[:note_id])
    if @note.user_id == current_user.id
      @note.message = 0
      @note.save
    end

    @comment = Comment.new(:commentable_id => @note.id)
    @comments = @note.comments

    respond_to do |format|
      format.js # index.js.erb
      format.json { render json: @comments }
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @commentable = Object.const_get(params[:comment][:commentable_type]).find(params[:comment][:commentable_id])
    @comment = @commentable.comments.create(:comment => params[:comment][:comment])
    @comment.user_id = current_user.id

    @comment.comment = string_replace(2 , html_escape(@comment.comment)) # repalce the string

    respond_to do |format|
      if @comment.save
        if @comment.commentable_type=='Note'
          create_message(@commentable,@comment)
        end

        format.js 
        format.json { render json: @comment, status: :created, location: @comment }
      else
        format.js { render "index" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @comment = Comment.find(params[:id])
    @commentable = Object.const_get(@comment.commentable_type).find(@comment.commentable_id)

    respond_to do |format|
      if @comment.update_attributes(params[:comment])
        format.html { redirect_to @commentable, notice: 'Comment was successfully updated.' }
        format.json { respond_with_bip(@comment) }
      else
        format.html { render @commentable, notice: 'Comemnt was unsuccessfully updated.' }
        format.json { respond_with_bip(@comment) }
      end
    end
  end
  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy

    respond_to do |format|
      format.js 
    end
  end
  
  def dono
    @note_id = params[:note_id]

    respond_to do |format|
      format.js
    end
  end

  def authorized_user
    comment = current_user.comments.find_by_id(params[:id])
    redirect_to root_url if comment.nil?
  end

  def create_message(note,comment)
    @at_users = comment.comment.scan(/@[a-zA-Z0-9_]+/)
    if not note.user_id == current_user.id
      @message = comment.infos.create ({
        :user_id => note.user_id,
        :message => comment,
        :refer => 1
      })
      broadcast "/ats/new/#{@message.user_id}", "{ note_id: #{note.id}, meg_type: 'new_comment' }"
    end

    @at_users.each do |at_user|
      user = User.find_by_sql("SELECT users.* FROM users WHERE nickname='#{at_user.from(1)}'") #check user is exist
      if user.size == 1 and not user[0].id == note.user_id #the at_user is not the user who owner the note
        @message = comment.infos.create ({
          :user_id => user[0].id,
          :refer => 1,
          :message => comment
        })
        broadcast "/ats/new/#{@message.user_id}", "{ note_id: #{note.id}, meg_type: 'at_in_comment' }"
      end
    end
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.haml
-# encoding: utf-8

%li.row-fluid.js-comment(id="comment#{comment.id}")
  - user = User.find(comment.user_id)
  .span1
    = link_to image_tag(user.avatar_url(:small), :height => "30", :width => "30"), 
    user_path(user), :title => "#{user.nickname}" 
  .span11
    //disable rdiscount
    = best_in_place comment, :comment, :type => :input, :activator => "#editcomment#{comment.id}"
    .pull-right.live-timestamp(data-notetime="#{comment.created_at}")
    - if(comment.user_id == current_user.id)
      %span(id="editcomment#{comment.id}")= link_to "修改", "", :class => "small-link", :style => "display:none;", :remote => true
      = link_to "#removecomment#{comment.id}",'data-toggle' => "modal", :class => 'toremove small-link', :style => "display:none;" do
        %i.icon-remove
      .commentremove.modal.hide.fade{:id => "removecomment#{comment.id}", :commentid => "#{comment.id}", :style => "display: none;"}
        .modal-header
          %a.close(data-dismiss="modal") ×
          %h3 删除评论
        .modal-body
          %h3 确定删除吗？
        .modal-footer
          = link_to '删除', comment, :method => "delete",  "data-dismiss" => "modal", :class => "btn", :remote => true
          %a.btn{:href => "close", "data-dismiss" => "modal"} 取消
  %br
  %hr

app/views/comments/_comment_box.html.haml
-# encoding: utf-8

%ul.comment.unstyled
  -@comments.each do |comment| 
    = render :partial => "comments/comment", :locals => { :comment => comment }

app/views/comments/_form.html.haml
-if @comments.size > 0
  =link_to '查看详情', @comments[0].commentable, :class => '', :target => '_blank' 
%br
=form_for(@comment, :remote => true, :class => "form-horizontal") do |f| 
  -if @comment.errors.any?
    #error_explanation
      %h2
        =pluralize(@comment.errors.count, "error") 
        prohibited this comment from being saved:

      %ul
      -@comment.errors.full_messages.each do |msg|
        %li= msg

  =f.hidden_field :commentable_id 
  =f.hidden_field :commentable_type, :value => 'Note'
  .row-fluid
    .span10=f.text_field :comment
    .span2=f.submit "评论", :class => "btn-info"

app/views/comments/_form_task.html.haml
= form_for(@comment, :url => comments_path, :method => "post", :remote => true, :class => "form-horizontal") do |f| 
  - if @comment.errors.any?
    #error_explanation
      %h2
        =pluralize(@comment.errors.count, "error") 
        prohibited this comment from being saved:

      %ul
      - @comment.errors.full_messages.each do |msg|
        %li= msg
  = f.text_area :comment, :rows => "3"
  - @commentable = @task || @event || @document
  = f.hidden_field :commentable_id, :value => @commentable.id
  = f.hidden_field :commentable_type, :value => @commentable.class.name
  = f.submit "评论", :class => "btn-info pull-right"

app/views/comments/create.js.erb
(function() {
  var $link = $('#comments_link<%= @comment.commentable_id %>');
  var num = $link.text().match(/\d+/);
  num = num * 1 + 1 ;
  $link.text( $link.text().replace(/\d+/, num) );

  var $list = $('#comments_list<%= @comment.commentable_id %>');
  $list.find('ul.comment').append( "<%= j render :partial => 'comments/comment', :locals => { :comment => @comment } %>" );
  $list.find('#new_comment')[0].reset();
  $list.find('#comment_comment').focus();

  setTimeout( function() {
    $('.best_in_place').best_in_place();
  }, 100 );
}());

app/views/comments/destroy.js.erb
<% if @comment.valid? %>
    $('#main-contents').find('#comment<%= @comment.id%>').remove();
    
    var $item = $('#note<%= @comment.commentable_id %>').find('div.item');
    var $link = $('#comments_link<%= @comment.commentable_id%>');
    var num = $link.text().match(/\d+/);
    num = Number(num)-1;
    $link.text( $link.text().replace(/\d+/, num) );

<% end %>

app/views/comments/dono.js.erb
(function() {
  var $link = $('#comments_link<%= @note_id %>');
  $link.attr("href","<%= comments_path(:note_id => @note_id)%>");
}());

app/views/comments/index.js.erb
(function() {
  var $link = $('#comments_link<%= @note.id %>');
  $link.text( $link.text().replace(/\d+/, <%= @comments.length %>) );
  $link.attr("href","<%= dono_comments_path(:note_id => @note.id )%>");

  var $list = $('#comments_list<%= @note.id %>');
  $list.html( "<%= j render( 'comments/comment_box') %>" );
  $list.append( "<%= j render( 'comments/form') %>" );
  $list.find('#comment_comment').focus();

  setTimeout( function() {
    $('.best_in_place').best_in_place();
  }, 100 );
}());