config/routes.rb
Rednote::Application.routes.draw do

  resources :documents, :only => [:index, :create, :show, :destroy, :update]

  match '/mails', :to => 'mails#index'
  match '/mails/interview', :to => 'mails#interview'
  match '/mails/invite', :to => 'mails#invite'

  match '/calendar(/:year(/:month))' => 'projects#index', 
    :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  root :to => "projects#index"
  mount Ckeditor::Engine => '/ckeditor'

  resources :projects
  resources :events do
    collection do
      get 'get_events'
      post 'move'
      post 'resize'
    end
  end
    
  
  resources :debits, :only => [:new, :destroy] do
    collection do
      post 'unwaiting'
    end
  end

  resources :books, :only => [ :new, :index, :create, :show ] do
    collection do 
      post 'borrow'
    end
  end

  resources :comments, :only => [:new, :index, :create, :destroy, :update] do 
    collection do 
      get 'dono'
    end
  end

  resources :likes, :only => [:create, :update, :destroy]
  resources :attachements, :only => [:create]

  devise_for :users
  resources :users, :only => [:show] do
    member do
      get 'mytags'
      get 'mytasks'
      get 'mycomments'
      get 'page'
      get 'myats'
    end
    collection do
      get 'nickname'
      match 'avatar'
      match 'avatar_update'
      match 'nickname_update'
      get 'search_nickname'
      get 'search_email'
      match 'crop_update'
    end
  end

  resources :notes do
    collection do
      get 'page'
      get 'taglist'
    end
  end

  resources :tasks do
    member do
      get 'show_partial'
    end
    collection do
      get 'mytasks'
      get 'history'
      get 'discuss'
      get  'set_status'
      post 'set_tag'
      get 'assign'
    end
  end

end

app/models/user.rb
# encoding: utf-8
# == Schema Information
#
# Table name: users
#
#  id                     :integer(4)      not null, primary key
#  email                  :string(255)     default(""), not null
#  encrypted_password     :string(255)     default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer(4)      default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#  created_at             :datetime        not null
#  updated_at             :datetime        not null
#  nickname               :string(255)
#  avatar                 :string(255)
#  preview                :string(255)
#

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_tagger

  acts_as_messageable
  
  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :nickname, 
                  :avatar, :avatar_cache, :preview, :preview_cache

  has_many :notes,     :dependent => :destroy
  has_many :comments,  :dependent => :destroy
  has_many :tasks,     :dependent => :destroy
  has_many :likes,     :dependent => :destroy
  has_many :attachements, :dependent => :destroy
  has_one  :debit,     :dependent => :destroy
  has_many :books
  has_many :answers,   :dependent => :destroy
  has_many :questions, :dependent => :destroy
  has_many :infos,     :dependent => :destroy
  has_many :projects,  :dependent => :destroy
  has_many :events,    :dependent => :destroy
  has_many :eventSeries, :dependent => :destroy
  has_many :documents, :dependent => :destroy

  mount_uploader :avatar, AvatarUploader
  mount_uploader :preview, PreviewUploader

  attr_accessor :crop_x, :crop_y, :crop_h, :crop_w
  after_update :reprocess_preview, :if => :cropping?

  def cropping?
      !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end

  def preview_geometry
      img = Magick::Image::read(self.preview.current_path).first
      @geometry = {:width => img.columns, :height => img.rows }
  end

  private

  def reprocess_preview
      self.preview.recreate_versions!
  end

  def self.list_user_options 
    userlist = User.select("id, nickname").map {|x| [x.id, x.nickname] }
    [[0, "Unassigned"]] + userlist
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :default_avatar, :except => [:search_nickname, :search_email]
  before_filter :all_users, :except => [:search_nickname, :search_email]

  def show
    @user = User.find(params[:id])

    cookies[:limit] = 20
    cookies[:offset] = 20 # note offset

    @avatar = @user.avatar
    @nickname = @user.nickname
    @notes = @user.notes.offset(0).limit(cookies[:limit]).reverse_order

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /users/page
  # get next page by ajax request
  def page
    @user = User.find(params[:id])

    @notes = @user.notes.offset(cookies[:offset].to_i).limit(cookies[:limit]).reverse_order
    cookies[:offset] = @notes.size + cookies[:offset].to_i

    respond_to do |format|
      if @notes.count() > 0
        format.js
      else
        format.js { render :nothing => true }
      end
    end
  end

  def mycomments
    @user = User.find(params[:id])
    @avatar = @user.avatar
    @nickname = @user.nickname
    @comments = @user.comments

    @comments.reverse!

    respond_to do |format|
      format.html { render 'show' }
      format.js { render 'show' }
    end
  end

  def mytasks
    @user = User.find(params[:id])

    @assigned_to_me_tasks = Task.find_all_by_assigned_to(@user.id)

    respond_to do |format|
      format.html { render 'show' }
      format.js { render 'show' }
    end
  end

  def mytags
    @user = User.find(params[:id])
    @avatar = @user.avatar
    @nickname = @user.nickname
    @notes = Note.find_by_sql("SELECT notes.* FROM notes WHERE id IN (SELECT note_id FROM likes WHERE user_id=#{@user.id} ) ORDER BY created_at DESC")

    respond_to do |format|
      format.html { render 'show' }
      format.js { render 'show' }
    end
  end

  def myats
    @user = User.find(params[:id])
    @messages = @user.infos

    respond_to do |format|
      format.html { render 'show' }
      format.js { render 'show' }
    end
  end

  def avatar
    respond_to do |format|
      format.html { render 'settings' }
      format.js { render 'devise/registrations/edit' }
    end
  end

  def nickname
    @user = current_user

    respond_to do |format|
      format.html { render 'settings' }
      format.js { render 'devise/registrations/edit' }
    end
  end

  def avatar_update
    current_user.preview = params[:user]["preview"]
    current_user.preview_cache = params[:user]["preview_cache"]
    current_user.save!

    respond_to do |format|
      format.html {redirect_to '/users/avatar'}
    end
  end

  def nickname_update
    current_user.nickname = params[:user][:nickname]
    current_user.save!

    respond_to do |format|
      format.html {redirect_to '/users/nickname'}
    end
  end

  def crop_update
    @user = current_user
    current_user.crop_x = params[:user]["crop_x"]
    current_user.crop_y = params[:user]["crop_y"]
    current_user.crop_h = params[:user]["crop_h"]
    current_user.crop_w = params[:user]["crop_w"]
    current_user.avatar = current_user.preview
    current_user.save!

    redirect_to user_path(current_user)
  end

  def search_nickname
    @name = params[:val]
    @user_by_nickname = User.find_by_sql("SELECT users.* FROM users WHERE nickname='#{@name}'")

    if @user_by_nickname.size == 0  
      render :inline => "unexsit" 
    else 
      render :inline => "exsit" 
    end
  end

  def search_email
    @email = params[:val]
    @user_by_email = User.find_by_email("#{@email}")

    if @user_by_email 
      render :inline => "exsit" 
    else 
      render :inline => "unexsit" 
    end
  end

  private
  def default_avatar
    @user = current_user

    if @user.avatar.blank? 
      @user.avatar = File.open('public/images/avatar.jpg')
      @user.preview = @user.avatar 
      @user.save
    end
  end

  def all_users
    @users = User.all
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatar.html.haml
#preview_form
  = form_for current_user, :html => {:multipart => true}, :url => { :action => 'avatar_update'} do |f|
    %p
      = f.file_field :preview 
      = f.hidden_field :preview_cache
      = f.submit "上传"

.jcrop
  .row
    .span4
      = image_tag current_user.preview_url(:large), :id => "cropbox", :date => current_user.preview_geometry[:width]
    
    .span3
      .preview1
        = image_tag current_user.preview_url(:large), :id => "preview1"
      大尺寸图像180x180像素
    .span1.offset1
      .preview2
        = image_tag current_user.preview_url(:large), :id => "preview2"
      小尺寸图48x48像素
    = form_for current_user, :url => { :action => "crop_update" } do |f|
      - for attribute in [:crop_x, :crop_y, :crop_h, :crop_w]
        = f.hidden_field attribute, :id => attribute
      .pull-right
        = f.submit "确定", :class => "btn btn-large btn-primary"

app/views/users/_myats.html.haml
%h4动态
- @messages.each do |message|
  - css = message.read == 0 ? "muted" : ""
  %strong{:class => css }
    - if message.message_type == "Note"
      = "有人提到了你：#{message.message.summary}".html_safe
      = link_to '查看', message.message, :class => 'small-link'
    - elsif message.message_type == "Comment"
      = "有新评论：#{message.message.comment}".html_safe
      = link_to '查看', message.message.commentable, :class => 'small-link'
  %br

app/views/users/_mycomments.html.haml
#comment_list
  -@comments.each do |comment|
    %div{ :id => "comment#{comment.id}"}
      %div{ "data-toggle" => "collapse", "data-target" => "#note_link_commentid#{comment.id}", "data-parent" => "#comment_list" }
        %i.icon-chevron-down
        = comment.comment.html_safe
        = link_to "#removecomment#{comment.id}", 'data-toggle'=>"modal", :class => 'small-button' do
          %i.icon-remove
        .commentremove.modal.hide.fade{ :id => "removecomment#{comment.id}", "style" => "display:none"}
          .modal-header
            %a.close{ "data-dismiss" => "modal" }
              %i.icon-remove
            %h3删除评论

          .modal-body
            %h3确定删除吗?
          .modal-footer
            = link_to '删除', comment, :method => "delete",  "data-dismiss" => "modal", :class => "btn", :remote => true
            = link_to '取消', "close", :class=>"btn", "data-dismiss" => "modal"

      .collapse.in{:id => "note_link_commentid#{comment.id}"}
        %br
        .row-fluid
          - note = Note.find(comment.commentable_id)
          .span1
            = image_tag(User.find(note.user_id).avatar_url(:small), :height => "40", :width => "40", :class => "avatar")
          .span11.item
            = note.summary.html_safe
            .live-timestamp{ "data-notetime" => "#{note.created_at}"}
    %hr

app/views/users/_mytags.html.haml
%ul.list
  = render "notes/list"

app/views/users/_mytasks.html.haml
.tabbable{ :style=>"margin-bottom: 9px;"}
  .tab-content
    .tab-pane.active#assigned_to_me
      .tasklist
        - @assigned_to_me_tasks.each do |task|
          = render :partial => 'tasks/note', :locals => { :task => task, :show => :edit }

app/views/users/_nickname.html.haml
= form_for @user, :url => { :action => 'nickname_update'} do |f|
  .field
    = f.label "昵称："
    = f.text_field :nickname, :size => 25
    = f.submit "确定", :class => "btn btn-large btn-primary"

app/views/users/_sidebar.html.haml
.board
  = render :partial => 'userinfo', :locals => { :user => @user }

  %h3同事
  - @users.each do |user|
    %p
      = link_to user.nickname, user_path(user), :method => :get

app/views/users/_smallinfo.html.haml
- # encoding: utf-8

.thumbnail.useritem{:id => "user#{user.id}"}
  = link_to image_tag(user.avatar_url()), mytasks_user_path(user.id)
  .caption
    - total = 0.1 # a small value, but not be zero
    - done = 0.0
    - tasks = Task.find_by_sql("select * from tasks where assigned_to=#{user.id} and ( status < 2 or (status=2 and finish_at >= '#{Date.today.beginning_of_week.to_datetime.to_formatted_s(:db)}'))")
    - tasks.each do |task|
      - total += task.estimate.to_f
      - done += task.estimate.to_f if task.status == Task::DONE
    %p
      = user.nickname
      %br
      任务数:
      = tasks.count if tasks
      %br
      .pull-left 承担任务:
      .progress.small-progress
        .bar{ :style=>"width: #{100.0*total/Task::MAX_WEEK_TASK_TIME}%;" }
          = total
      .pull-left 完成任务:
      .progress.small-progress
        .bar{ :style=>"width: #{100.0*done/total}%;"}
          = done

app/views/users/_userinfo.html.haml
.row-fluid
  = link_to image_tag(user.avatar_url(:thumb)), nickname_users_path, :class => "span4 thumbnail"
  .span7
    %h2.title
      = user.nickname
    发布数: 
    = user.notes.size 
    %br
    注册时间: 
    = user.created_at.to_date 
    %br
    上次登录ip:
    = user.last_sign_in_ip if user.last_sign_in_ip 
    %br
    .progress
      .bar { :style => "width:44%;" }
%br

app/views/users/done.html.erb
<%= render "user_info"%>
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><a href="/users/index">全部动态</a></li>
      <li><a href="/users/mycomments">我的评论</a></li>
      <li><a href="/users/comments">我被评论</a></li>
      <li><a href="/users/reading">Reading</a></li>
      <li class="active"><a href="/users/done">Done</a></li>
    </ul>
  </div>
  <ul class="list">
    <%= render "notes/list" %>
  </ul>
</div>

app/views/users/index.js.erb
<%# encoding: utf-8 %>

(function() {

  var $space = $('#myself').find('div.mycontent');

  <% if controller.action_name == "index" or controller.action_name == "mytags" %> 
      $space.html( "<%= j render :partial => 'mytags' %>" ); 
  <% else %> 
      $space.html( "<%= j render :partial => 'mycomments' %> " );
  <% end %>;


  commentsManager.bindHandlers();
  rednote.updateNoteTime();
})();

app/views/users/page.js.erb
(function() {
  $notes = $('#main-contents ul.list');
  $notes.append( "<%= j render 'notes/list' %> " );
});

app/views/users/settings.html.haml
.well#settings
  #tabspin
    %ul.nav.nav-tabs
      %li.active
        = link_to "修改昵称", nickname_users_path, :remote => true, "data-toggle" => "tab", "data-target" => "#"
      %li
        = link_to "修改头像", avatar_users_path, :remote => true, "data-toggle" => "tab", "data-target" => "#" 
      %li
        = link_to "修改密码", edit_user_registration_path, :method => :get, :remote => true, "data-toggle" => "tab", "data-target" => "#"
  #modify
    - if controller.action_name == 'edit'
      = render :partial => "devise/registrations/edit"
    - else
      = render :partial => controller.action_name 

app/views/users/show.js.erb
<%# encoding: utf-8 %>

(function() {
  var $space = $('#myself').find('div.mycontent');

  <% if controller.action_name == "show" or controller.action_name == "mytags" %> 
      $space.html( "<%= j render :partial => 'mytags' %>" ); 
  <% elsif controller.action_name == "mytasks" %> 
      $space.html( "<%= j render :partial => 'mytasks' %>" ); 
  <% elsif controller.action_name == "myats" %> 
      $space.html( "<%= j render :partial => 'myats' %>" ); 
  <% else %> 
      $space.html( "<%= j render :partial => 'mycomments' %> " );
  <% end %>;
})();