config/routes.rb
Rednote::Application.routes.draw do

  resources :documents, :only => [:index, :create, :show, :destroy, :update]

  match '/mails', :to => 'mails#index'
  match '/mails/interview', :to => 'mails#interview'
  match '/mails/invite', :to => 'mails#invite'

  match '/calendar(/:year(/:month))' => 'projects#index', 
    :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}

  root :to => "projects#index"
  mount Ckeditor::Engine => '/ckeditor'

  resources :projects
  resources :events do
    collection do
      get 'get_events'
      post 'move'
      post 'resize'
    end
  end
    
  
  resources :debits, :only => [:new, :destroy] do
    collection do
      post 'unwaiting'
    end
  end

  resources :books, :only => [ :new, :index, :create, :show ] do
    collection do 
      post 'borrow'
    end
  end

  resources :comments, :only => [:new, :index, :create, :destroy, :update] do 
    collection do 
      get 'dono'
    end
  end

  resources :likes, :only => [:create, :update, :destroy]
  resources :attachements, :only => [:create]

  devise_for :users
  resources :users, :only => [:show] do
    member do
      get 'mytags'
      get 'mytasks'
      get 'mycomments'
      get 'page'
      get 'myats'
    end
    collection do
      get 'nickname'
      match 'avatar'
      match 'avatar_update'
      match 'nickname_update'
      get 'search_nickname'
      get 'search_email'
      match 'crop_update'
    end
  end

  resources :notes do
    collection do
      get 'page'
      get 'taglist'
    end
  end

  resources :tasks do
    member do
      get 'show_partial'
    end
    collection do
      get 'mytasks'
      get 'history'
      get 'discuss'
      get  'set_status'
      post 'set_tag'
      get 'assign'
    end
  end

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer(4)      not null, primary key
#  user_id    :integer(4)
#  owner_id   :integer(4)
#  name       :string(255)
#  summary    :string(255)
#  tags       :string(255)
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Project < ActiveRecord::Base
  attr_accessible :name, :owner_id, :summary, :tags
  acts_as_commentable
  belongs_to :user
  has_many :tasks,  :dependent => :destroy
  has_many :documents,  :dependent => :destroy
  
  validates :name,    :presence => true,
                      :length   => { :maximum => 50 }
  validates :summary, :presence => true,
                      :length   => { :maximum => 200 }
  validates :user_id, :presence => true
  has_associated_audits
  
end

app/controllers/projects_controller.rb
# encoding: utf-8

class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @project = Project.new

    respond_to do |format|
      format.html # index.html.erb
      format.js # index.js.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.js # show.js.erb
      format.json { render json: @project }
    end
  end

  def history
    #mock
    respond_to do |format|
      format.html # history.html.erb
      format.js # history.js.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  #def edit
  #end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.js # create.js.erb
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { redirect_to projects_path, notice: 'Project was successfully created.' }
        format.js # create.js.erb
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  #def update
  #end

  # DELETE /projects/1
  # DELETE /projects/1.json
  #def destroy
  #end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def month_link(month_date)
    link_to(I18n.localize(month_date, :format => "%B"), {:month => month_date.month, :year => month_date.year})
  end

  # custom options for this calendar
  def event_calendar_options
    { 
      :year => @year,
      :month => @month,
      #:use_all_day => true,
      :event_strips => @project_strips,
      :month_name_text => I18n.localize(@shown_month, :format => "%B %Y"),
      :previous_month_text => "<< " + month_link(@shown_month.prev_month),
      :next_month_text => month_link(@shown_month.next_month) + " >>"
    }
  end

  def event_calendar
    calendar event_calendar_options do |args|
      proj = args[:event]
      %(<a href="/projects/#{proj.id}" title="#{h(proj.project_list[0])}">#{h(proj.project_list[0])}</a>)
    end
  end
end

app/views/projects/_form.html.haml
= simple_form_for @project, :wrapper => :bootstrap do |f|
  -if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  = f.input :name
  = f.input :tags
  = f.input :summary
  .actions
    %button.btn.btn-primary.pull-right{:type=>"submit"} 新建项目

app/views/projects/_knowledgebase.html.haml
- # encoding: utf-8

Knowledgebase

app/views/projects/_sidebar.html.haml
= render 'events/list'

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project
|
= link_to 'Back', projects_path

app/views/projects/index.html.haml
- # encoding: utf-8

.board
  %h1 项目
  - @projects.each do |project|
    .page-header
      %h2
        = link_to project.name, project
        %small= project.summary
  .page-header
    %h3
      快速帮助
  %ul
    %li
      %strong 写明确的任务
      这个任务应该是你当前具体要做的事情，而不是你的近期工作目标。
    %li
      %strong 给自己的任务估时
      默认估时是0天，表示这个事情可以很快搞定。如果估时超过3天，那么这个任务就是不明确的，需要对它进行细化和分解，重新创建任务。
    %li
      %strong 任务描述尽量写长点
      写的任务描述让别人能看懂，如果别人看不懂，那么过一段时间，你自己也就看不懂了。
    %li
      %strong ...
  .form-actions
    = render 'form'

app/views/projects/knowledgebase.js.erb
<%# encoding: utf-8 %>

(function() {
$('#projectcontent').html( "<%= j render( :partial => 'knowledgebase' ) %>" );
}());

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path

app/views/projects/show.html.haml
- # encoding: utf-8

.board
  %ul.nav.nav-pills
    %li.active= link_to "讨论", "#questioncontent"
    %li= link_to "任务", "#taskcontent"
    %li= link_to "文档", "#documentcontent"
    %li= link_to "回顾", "#historycontent"

  .page-header
    .pull-right
      - User.all.each do |user|
        .red-avatar.useritem{:id => "user#{user.id}"}
          = link_to image_tag(user.avatar_url(:small)), mytasks_user_path(user), :class => "thumbnail"
    %h2= @project.name

  #questioncontent
    = link_to "讨论", discuss_tasks_path(:project => @project.id), :id => "latest_commentslink", :remote => true
  #taskcontent
    = link_to "任务", tasks_path(:project => @project.id), :id => "taskprogresslink", :remote => true
  #documentcontent
    = link_to "文档", documents_path(:project => @project.id), :id => "documentfiles", :remote => true
  #historycontent
    %h3
      = link_to history_tasks_path(:project => @project.id), :id => "oldtasklink", :remote => true, "data-toggle" => "collapse", "data-target" => "\#historylist" do
        查看回顾
        %i.icon-chevron-down
  #historylist